version: '3.8'

services:
  db:
    image: mysql:9.1
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/mydatabase"
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      YOUR_SECRET_KEY: ${YOUR_SECRET_KEY}
    depends_on:
      - db
      - kafka

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  email-sender:
    build: ./email-sender
    depends_on:
      - backend
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      YOUR_MAILJET_API_KEY: ${YOUR_MAILJET_API_KEY}
      YOUR_MAILJET_SECRET_KEY: ${YOUR_MAILJET_SECRET_KEY}
      YOUR_SENDER_EMAIL_ADDRESS: ${YOUR_SENDER_EMAIL_ADDRESS}
    ports:
      - "8081:8080"

  scheduler:
    build: ./scheduler
    depends_on:
      - backend
      - kafka
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/mydatabase"
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    ports:
      - "8082:8080"

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
